Expanded landing page documentation
skypyproject/skypy pull request #228
Opened 2020-07-15 13:23 UTC by itrharrison

## Description
An expanded landing page for the readthedocs to include some extra information to make it easier for new users and contributors to know what to do, such as:
- Summary of SkyPy features
- Links to / streaming in of LICENSE.rst, CODE_OF_CONDUCT.md, CONTRIBUTING.md, CITATION
- Requirements, how to install, running tests, importing the package, running examples
- Any other ideas?

Merging this closes #224 

## Checklist
- [X] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/master/CONTRIBUTING.md)
- [ ] Write unit tests
- [X] Write documentation strings
- [ ] Assign someone from your working team to review this pull request
- [ ] Assign someone from the infrastructure team to review this pull request

2020-09-02 10:25 UTC, ntessore commented on docs/importing_skypy.rst
> +    >>> from skypy.galaxy import *  # NOT recommended # doctest: +SKIP
Why not? If we don't recommend that then why are we setting `__all__`?

2021-01-28 10:32 UTC, ntessore commented
Since there have been some changes that address this partially, could we retool this PR to only include the parts of (README.rst on the landing page that cover summary and installation? That focuses the fairly broad scope a little.

See [literal include start-after, end-before](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude). One could mark the portion of README.rst to be included explicitly with `.. docs-start`, `.. docs-end` comments.

2021-06-21 09:33 UTC, ntessore commented on docs/install.rst
> +..     of ``SkyPy`` itself may result in a corrupted installation.
hard disagree, we are not a Python tutorial

2021-06-21 09:34 UTC, ntessore commented on docs/install.rst
> +  and documentation builds.
It might be better to describe how to install the requirements from the setup.cfg, including the various extras?

2021-06-22 12:48 UTC, ntessore commented on skypy/__init__.py
> +__minimum_astropy_version__ = '3.2'
```suggestion
```

2021-06-22 12:48 UTC, ntessore commented on docs/conf.py
> +
```suggestion
```

2021-06-22 12:48 UTC, ntessore commented on docs/conf.py
> +""".format(skypy)
```suggestion
"""
```

2021-06-22 12:48 UTC, ntessore commented on docs/importing_skypy.rst
> +    >>> from skypy.galaxy import *  # NOT recommended # doctest: +SKIP
```suggestion
```

2021-06-22 12:48 UTC, ntessore commented on docs/index.rst
> +   running_skypy
```suggestion
```

2021-06-22 12:48 UTC, ntessore commented on docs/install.rst
> +directory, and can be compiled using ``pdflatex``.
```suggestion
```

2021-06-22 12:48 UTC, ntessore commented on docs/running_skypy.rst
> +containing sampled redshifts and magnitudes for red and blue galaxies.
```suggestion
```

2021-06-22 12:48 UTC, ntessore commented on docs/index.rst
> +
```suggestion
```

2021-06-22 12:48 UTC, ntessore commented on docs/index.rst
> +   How to Cite SkyPy <https://github.com/skypyproject/skypy/blob/master/CITATION>
```suggestion
```

2021-06-22 13:10 UTC, rrjbca requested changes

2021-06-22 13:10 UTC, rrjbca commented on docs/index.rst
> +   <hhttps://github.com/skypyproject/skypy/blob/master/CITATION>`_.
```suggestion
   <https://github.com/skypyproject/skypy/blob/main/CITATION.rst>`_.
```

2021-06-22 13:10 UTC, rrjbca commented on docs/index.rst
> +
```suggestion
```

2021-06-22 13:10 UTC, rrjbca commented on docs/index.rst
> +as well as synthetic observed data based on those objects.
```suggestion
This package contains methods for modelling the Universe, galaxies and the
Milky Way. SkyPy simulates populations of astronomical objects, generating
random realisations of intrinsic and observed properties, with the
intention the simulations can then be compared to data as part of an inference
pipeline.
```

2021-06-22 13:17 UTC, rrjbca approved these changes

2021-06-22 13:20 UTC, merged