Changing fsky to sky_area
skypyproject/skypy pull request #314
Opened 2020-10-04 15:40 UTC by philipp128

## Description
This PR solves #309 . `fsky` was changed to `sky_area` which has to be given in sr or deg2 units.

## Checklist
- [ ] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/master/CONTRIBUTING.md)
- [ ] Write unit tests
- [ ] Write documentation strings
- [ ] Assign someone from your working team to review this pull request
- [ ] Assign someone from the infrastructure team to review this pull request

2020-10-05 07:26 UTC, ntessore commented
Looks good! Could you please use Astropy's [`quantity_input`](https://docs.astropy.org/en/stable/api/astropy.units.quantity_input.html) decorator in the form `@quantity_input(sky_area=u.sr)` for the functions? Then please remove the explicit conversion you added, and just do

    dN_dz = (cosmology.differential_comoving_volume(redshift)*sky_area).to_value('Mpc3')

— Astropy units will do the rest.

2020-10-05 08:01 UTC, JonathanDHarris commented
@ntessore @philipp128  do we need to update the yml files in `examples`?

2020-10-05 08:14 UTC, ntessore commented
> @ntessore @philipp128 do we need to update the yml files in `examples`?

Yes, that's right, good catch!

@philipp128: We don't have an automatic way of constructing unitful quantities yet, so you will need to change `fsky: ...` to `sky_area: !astropy.units.Quantity ['1 deg2']` or so in the examples.

2020-10-05 10:13 UTC, philipp128 commented
> Looks good! Could you please use Astropy's [`quantity_input`](https://docs.astropy.org/en/stable/api/astropy.units.quantity_input.html) decorator in the form `@quantity_input(sky_area=units.sr)` for the functions? Then please remove the explicit conversion you added, and just do
> 

Would this raise an error if the unit is `deg2`?

2020-10-05 11:10 UTC, ntessore requested changes
some matters of style, but looking good overall

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/redshift.py
> +    >>> sky_area = 1 * units.degree * units.degree
better to construct the deg2 unit than to multiply 1 degree time the degree unit 

```suggestion
    >>> sky_area = 1*units.deg**2
```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/redshift.py
> +        sr or deg2.
```suggestion
    sky_area : `~astropy.units.Quantity`
        Sky area over which galaxies are sampled. Must be in units of solid
        angle.
```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/redshift.py
> +    >>> sky_area = 1 * units.degree * units.degree
```suggestion
    >>> sky_area = 1*units.deg**2
```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/redshift.py
> +
no need for that
```suggestion

```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/tests/test_redshift.py
> +    sky_area = 1.0 * units.degree * units.degree
```suggestion
    sky_area = 1.0 * units.deg**2
```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/tests/test_redshift.py
> +        cosmo.differential_comoving_volume(z).to_value('Mpc3/sr')
```suggestion
    density *= (sky_area * cosmo.differential_comoving_volume(z)).to_value('Mpc3')
```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/tests/test_redshift.py
> +    from astropy.units.core import UnitsError
already have `units`
```suggestion
```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/tests/test_redshift.py
> +
no need to check these cases
```suggestion

```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/tests/test_redshift.py
> +    with pytest.raises(UnitsError):
use `units.UnitsError` instead of importing from the internal `units.core`

```suggestion
    with pytest.raises(units.UnitsError):
```

2020-10-05 11:10 UTC, ntessore commented on skypy/galaxy/tests/test_schechter.py
> +    sky_area = 1.0 * units.degree * units.degree
```suggestion
    sky_area = 1.0 * units.deg**2
```

2020-10-05 11:32 UTC, philipp128 commented on skypy/galaxy/redshift.py
> +def schechter_lf_redshift(redshift, M_star, phi_star, alpha, m_lim, sky_area,
Is it necessary here, as it will be evaluated in 'redshifts_from_comoving_density' anyway?

2020-10-05 11:33 UTC, philipp128 commented on skypy/galaxy/_schechter.py
> +    sky_area : astropy quantity
Ok. What exactly does it mean? So, what are the quotation marks and the `~` doing?

2020-10-05 11:37 UTC, ntessore commented on skypy/galaxy/redshift.py
> +def schechter_lf_redshift(redshift, M_star, phi_star, alpha, m_lim, sky_area,
You're right in that it is not necessary. However, the function expects a quantity, so it's good to mark it as such, and we might one day change the implementation to not call the other function any more and bail us out.

2020-10-05 11:38 UTC, ntessore commented on skypy/galaxy/_schechter.py
> +    sky_area : astropy quantity
they make a nice link to the Astropy docs

2020-10-21 10:23 UTC, rrjbca requested changes
Looks great just a couple of small changes

2020-10-21 10:23 UTC, rrjbca commented on examples/gravitational_wave_rates.yml
> +sky_area: !astropy.units.Quantity ['1 deg2']
```suggestion
sky_area: 1 deg2
```
PR #316 has been merged so if you update your branch this syntax should now work. Also in the other example config files.

2020-10-21 10:23 UTC, rrjbca commented on skypy/galaxy/tests/test_redshift.py
> +                cosmo.differential_comoving_volume(z)).to_value('Mpc3')
```suggestion
    density *= (sky_area * cosmo.differential_comoving_volume(z)).to_value('Mpc3')
```

2020-10-21 10:23 UTC, rrjbca commented on skypy/galaxy/tests/test_redshift.py
> +    # test that error is returned if wrong unit is given
```suggestion
    # Test that an error is raised if sky_area has the wrong units
```

2020-10-21 10:23 UTC, rrjbca commented on skypy/galaxy/tests/test_redshift.py
> +    # test that error is returned if no unit is given
```suggestion
    # Test that an error is raised if sky_area has no units
```

2020-10-22 14:29 UTC, rrjbca reviewed
I just spotted that [`docs/pipeline/examples/lightcone.yml`](https://github.com/philipp128/skypy/blob/sky_fraction/docs/pipeline/examples/lightcone.yml) is still using `fsky: 1.0e-6` would recommend changing it to `sky_area: 0.05 deg2` so that the plot still has a similar number of galaxies to before.

2020-10-23 11:37 UTC, rrjbca approved these changes

2020-10-23 11:55 UTC, ntessore approved these changes
LGTM

2020-10-23 12:15 UTC, merged