Ipynb examples
skypyproject/skypy pull request #339
Opened 2020-10-07 14:52 UTC by itrharrison

## Description
Merging will close #335. Have added iPython notebooks making plots from the outputs of the current example config files.

## Checklist
- [X] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/master/CONTRIBUTING.md)
- [ ] Write unit tests
- [ ] Write documentation strings
- [ ] Assign someone from your working team to review this pull request
- [X] Assign someone from the infrastructure team to review this pull request

2020-10-07 15:18 UTC, Lucia-Fonseca requested changes

2020-10-07 15:18 UTC, Lucia-Fonseca commented on skypy/power_spectrum/tests/test_camb.py
> +    assert allclose(pzk, test_pzk[np.argsort(redshift), :], rtol=1.e-4)
it complains "no newline at the end of file"

2020-10-07 15:18 UTC, Lucia-Fonseca commented on skypy/power_spectrum/tests/test_class.py
> +
it complains "no newline at the end of file"

2020-10-09 13:29 UTC, Lucia-Fonseca requested changes
It looks very good! Great job, Ian.
Two small changes:
* Add `plt.show()` to avoid outputing unnecesary text
* Name of the config file for merger rates
* I still see `test_camb.py` and `test_class.py`.

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/abundance_matching.ipynb
> +    "plt.legend()"
```suggestion
    "plt.legend()"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/abundance_matching.ipynb
> +    "plt.yscale('log')"
```suggestion
    "plt.yscale('log')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/abundance_matching.ipynb
> +    "plt.xlabel('Group')"
```suggestion
    "plt.xlabel('Group')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/abundance_matching.ipynb
> +    "plt.ylabel('$m$')"
```suggestion
    "plt.ylabel('$m$')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/gravitational_wave_rates.ipynb
> +    "plt.ylabel('$m$')"
```suggestion
    "plt.ylabel('$m$')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/gravitational_wave_rates.ipynb
> +    "plt.xlabel('$z$')"
```suggestion
    "plt.xlabel('$z$')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/gravitational_wave_rates.ipynb
> +    "plt.xlabel('$m$')"
```suggestion
    "plt.xlabel('$m$')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/gravitational_wave_rates.ipynb
> +    "plt.yscale('log')"
```suggestion
    "plt.yscale('log')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/gravitational_wave_rates.ipynb
> +    "plt.xlabel('$R\\,$[yr$^{-1}$]')"
```suggestion
    "plt.xlabel('$R\\,$[yr$^{-1}$]')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/gravitational_wave_rates.ipynb
> +    "$ skypy merger_rates.yml --format fits\n",
Is the name of the file `merger_rates.yml` or `gravitational_wave_rates.yml`?

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/mccl_galaxies.ipynb
> +    "plt.ylabel('$m$')"
```suggestion
    "plt.ylabel('$m$')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/mccl_galaxies.ipynb
> +    "plt.xlabel('$z$')"
```suggestion
    "plt.xlabel('$z$')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/mccl_galaxies.ipynb
> +    "plt.xlabel('$m$')"
```suggestion
    "plt.xlabel('$m$')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/mccl_galaxies.ipynb
> +    "plt.xlabel('$d\\,$[kpc]')"
```suggestion
    "plt.xlabel('$d\\,$[kpc]')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/mccl_galaxies.ipynb
> +    "plt.xlabel('$|e|$')"
```suggestion
    "plt.xlabel('$|e|$')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/mccl_galaxies.ipynb
> +    "plt.xlabel('$\\\\theta\\,$[rad]')"
```suggestion
    "plt.xlabel('$\\\\theta\\,$[rad]')"
    "plt.show()"
```

2020-10-09 13:29 UTC, Lucia-Fonseca commented on examples/mccl_galaxies.ipynb
> +    "plt.xlabel('$c_{i}$')"
```suggestion
    "plt.xlabel('$c_{i}$')"
    "plt.show()"
```

2020-10-09 13:34 UTC, jucordero commented
I think you can also do
`plt.xlabel('This is an x label');`
to avoid extra text output in the notebooks without the need of a `plt.show`

2020-10-09 13:45 UTC, Lucia-Fonseca commented
That works too, thanks @jucordero!
> I think you can add a semicolon at the end of a statement
> > `plt.xlabel('This is an x label');`
> > to avoid extra text output in the notebooks without the need of a `plt.show`

2020-10-16 10:53 UTC, Lucia-Fonseca requested changes

2020-10-16 10:53 UTC, Lucia-Fonseca commented on examples/gravitational_wave_rates.ipynb
> +    "$ skypy merger_rates.yml --format fits\n",
This still needs to be addressed.

2020-10-19 14:05 UTC, rrjbca reviewed
Is the intention that the user would run these notebooks themselves? I think they make more sense as part of the documentation (perhaps using [nbsphinx](https://nbsphinx.readthedocs.io/en/0.7.1/)?) but if that is the case they should probably be in the `docs` directory not the `examples` directory. Particularly because everything in `examples` is mirrored to the [`skypyproject/examples`](https://github.com/skypyproject/examples) repository and we shouldn't distribute them in this way if we don't expect the user to run them.

2020-10-20 14:33 UTC, Lucia-Fonseca commented
The idea is to have something similar to CAMB DEMO 
https://camb.readthedocs.io/en/latest/CAMBdemo.html

2020-10-20 15:22 UTC, Lucia-Fonseca approved these changes
Looks good.

2020-10-27 14:42 UTC, rrjbca commented on skypy/power_spectrum/tests/test_camb.py
> +    assert allclose(pzk, test_pzk[np.argsort(redshift), :], rtol=1.e-4)
```suggestion
    assert allclose(pzk, test_pzk[np.argsort(redshift), :], rtol=1.e-4)

```

2020-10-27 14:42 UTC, rrjbca commented on skypy/power_spectrum/tests/test_class.py
> +
```suggestion

```

2020-10-27 14:44 UTC, rrjbca approved these changes
These look good, let's merge them as they are and work out how we want to incorporate them with the documentation in the future.

2020-10-27 14:49 UTC, merged