sample positions uniformly over HEALPix pixel
skypyproject/skypy pull request #344
Opened 2020-10-09 14:29 UTC by ntessore

## Description

Adds the `uniform_in_pixel` function to uniformly sample positions over an individual HEALPix pixel.

## Checklist
- [x] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/master/CONTRIBUTING.md)
- [ ] Write unit tests
- [ ] Write documentation strings
- [ ] Assign someone from your working team to review this pull request
- [ ] Assign someone from the infrastructure team to review this pull request

2020-10-19 13:50 UTC, rrjbca requested changes
One concern I have is there is no protection against an implementation error resulting in `over` being less than one, which could lead to getting stuck in the while loop. Perhaps defining a separate function `_oversampling_factor(nside)` we could test that the result is always greater than one for different values of `nside`? Thoughts?

2020-10-19 13:50 UTC, rrjbca commented on skypy/position/tests/test_healpy.py
> +        phi[ipix*20:(ipix+1)*20] = pos.ra.rad
```suggestion
    size = 20
    theta, phi = np.empty(npix*size), np.empty(npix*size)
    for ipix in range(npix):
        pos = uniform_in_pixel(nside, ipix, size=size)
        assert len(pos) == size
        theta[ipix*size:(ipix+1)*size] = np.pi/2 - pos.dec.rad
        phi[ipix*size:(ipix+1)*size] = pos.ra.rad
```

2020-10-19 13:50 UTC, rrjbca commented on skypy/position/tests/test_healpy.py
> +    assert len(pos) == 1000
```suggestion
    size = 1000
    pos = uniform_in_pixel(nside, ipix, size=size)
    assert len(pos) == size
```

2020-10-19 13:50 UTC, rrjbca commented on skypy/position/_uniform.py
> +    of with `nside` parameter.
```suggestion
    with a given `nside` parameter.
```

2020-10-19 13:50 UTC, rrjbca commented on skypy/position/_uniform.py
> +        Default is ``RING`` pixel ordering.
```suggestion
        If True assume ``NESTED`` pixel ordering, otherwise ``RING`` pixel
        ordering. Default is ``RING`` pixel ordering.
```

2020-10-23 08:31 UTC, ntessore commented
> One concern I have is there is no protection against an implementation error resulting in `over` being less than one

Over is the area of a circle covering a polygon, divided by the area of a polygon. It cannot be less than one, unless, as you say, the healp* implementation is wrong, in which case we cannot rely on anything else working either. So I don't see why we would worry about it.

2020-10-27 13:52 UTC, ntessore commented on skypy/position/_uniform.py
> +        sample = uniform_around(centre, area, int(miss*over))
```suggestion
        sample = uniform_around(centre, area, int(np.ceil(miss*over)))
```

2020-10-27 13:53 UTC, rrjbca approved these changes

2020-10-27 13:56 UTC, merged