Contributing section in documentation
skypyproject/skypy pull request #399
Opened 2021-01-20 13:38 UTC by Lucia-Fonseca

## Description
This pull request add the contributing guidelines to the documentation. This PR closes #396 .

## It needs
The file contributing.rst needs translation from md to 1st.
## Checklist
- [ ] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/master/CONTRIBUTING.md)
- [ ] Write unit tests
- [ ] Write documentation strings
- [ ] Assign someone from your working team to review this pull request
- [ ] Assign someone from the infrastructure team to review this pull request

2021-01-20 15:24 UTC, rrjbca reviewed
Some initial suggestions

2021-01-20 15:24 UTC, rrjbca commented on docs/index.rst
> +
Can we rename the directory `docs/contributing` to `docs/developer`

```suggestion
.. toctree::
   :maxdepth: 1

   developer/CONTRIBUTING

```

2021-01-20 15:24 UTC, rrjbca commented on README.rst
> +.. _Contributor Guidelines: docs/contributing/CONTRIBUTING.rst
Something like this...
```suggestion
.. _Contributor Guidelines: https://skypy.readthedocs.io/en/stable/developer/contributing.html
```

2021-01-20 15:24 UTC, rrjbca commented on docs/contributing/CONTRIBUTING.rst
> +=======================
```suggestion
Contributor Guidelines
======================
```

2021-01-21 10:10 UTC, Lucia-Fonseca commented
The documentation fails here but not locally on my machine.

2021-01-21 14:14 UTC, rrjbca commented on docs/index.rst
> +
```suggestion
```

2021-01-21 16:30 UTC, rrjbca commented on docs/developer/CONTRIBUTING.rst
> +  - ``Tests`` (Required) runs the `unit-tests`_ in four predefined environments; `latest supported versions`, `oldest supported versions`, `macOS latest supported` and `Windows latest supported`. Cli
```suggestion
  - ``Tests`` (Required) runs the `unit tests`_ in four predefined environments; `latest supported versions`, `oldest supported versions`, `macOS latest supported` and `Windows latest supported`. Click "Details" to view the output including any failures.
```

2021-01-21 17:04 UTC, rrjbca commented on docs/developer/CONTRIBUTING.rst
> +- Importing SkyPy should only depend on having `NumPy <https://www.numpy.org>`_, `SciPy <https://www.scipy.org/>`_ and `Astropy <https://www.astropy.org/>`_ installed.
```suggestion
- Importing SkyPy should only depend on having `NumPy <https://www.numpy.org>`_, `SciPy <https://www.scipy.org/>`_ and `Astropy <https://www.astropy.org/>`__ installed.
```

2021-01-22 08:42 UTC, Lucia-Fonseca commented on docs/developer/CONTRIBUTING.rst
> +- Importing SkyPy should only depend on having `NumPy <https://www.numpy.org>`_, `SciPy <https://www.scipy.org/>`_ and `Astropy <https://www.astropy.org/>`_ installed.
Why double underscore here?

2021-01-22 08:52 UTC, Lucia-Fonseca commented
This is OK now.

2021-01-22 09:36 UTC, rrjbca reviewed
We should keep `CONTRIBUTING.md` (GitHub recommend this in their community standards) with a single sentence and a link to the guidelines in the documentation.

2021-01-22 15:13 UTC, rrjbca requested changes

2021-01-22 15:13 UTC, rrjbca commented on docs/developer/CONTRIBUTING.rst
> +  5. Confirm the head fork is ``<your-account>/skypy`` and the compare branch is ```<your-branch-name>``
```suggestion
  4. Confirm that the base fork is ``skypyproject/skypy`` and the base branch is ``master``
  5. Confirm the head fork is ``<your-account>/skypy`` and the compare branch is ``<your-branch-name>``
```

2021-01-22 15:13 UTC, rrjbca commented on docs/developer/CONTRIBUTING.rst
> +- SkyPy is compatible with Python>=3.5 (see [setup.cfg](setup.cfg)). SkyPy *does not* support backwards compatibility with Python 2.x; `six`, `__future__` and `2to3` should not be used.
```suggestion
- SkyPy is compatible with Python>=3.6 (see `setup.cfg <https://github.com/skypyproject/skypy/blob/master/setup.cfg>`_). SkyPy *does not* support backwards compatibility with Python 2.x; `six`, `__future__` and `2to3` should not be used.
```

2021-01-22 15:13 UTC, rrjbca commented on docs/developer/CONTRIBUTING.rst
> +- Code is grouped into submodules based on broad science areas e.g. [galaxies](skypy/galaxy). There is also a [utils](skypy/utils) submodule for general utility functions.
```suggestion
- Code is grouped into submodules based on broad science areas e.g. `galaxies <https://skypy.readthedocs.io/en/stable/galaxy.html>`_. There is also a `utils <https://skypy.readthedocs.io/en/stable/utils/index.html>`_ submodule for general utility functions.
```

2021-01-25 15:58 UTC, rrjbca approved these changes

2021-01-25 15:58 UTC, merged