Remove docstring examples
skypyproject/skypy pull request #429
Opened 2021-02-16 15:57 UTC by rrjbca

## Description
Removes all docstring examples. Currently they only demonstrate trivial call patterns which should be adequately described by the list of parameters in the docstrings for each function. Any more complex examples that are required should probably be added to the examples directory instead where text, plots and code examples can be better used to explain and demonstrate what the function is doing. Docstring examples are also currently run as part of the tests which is unnecessary given that the actual unit tests should all cover the same simple call patterns.

## Checklist
- [x] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/master/CONTRIBUTING.md)
- [ ] Write unit tests
- [x] Write documentation strings
- [ ] Assign someone from your working team to review this pull request
- [x] Assign someone from the infrastructure team to review this pull request

2021-02-22 14:51 UTC, Lucia-Fonseca requested changes
Delete blank lines

2021-02-22 14:51 UTC, Lucia-Fonseca commented on skypy/galaxies/luminosity.py
Do we need this blank line?
```suggestion
```

2021-02-22 14:51 UTC, Lucia-Fonseca commented on skypy/galaxies/morphology.py
```suggestion
```

2021-02-22 14:51 UTC, Lucia-Fonseca commented on skypy/galaxies/morphology.py
```suggestion
```

2021-02-22 14:51 UTC, Lucia-Fonseca commented on skypy/galaxies/redshift.py
```suggestion
```

2021-02-22 14:51 UTC, Lucia-Fonseca commented on skypy/galaxies/redshift.py
```suggestion
```

2021-02-22 14:51 UTC, Lucia-Fonseca commented on skypy/galaxies/redshift.py
```suggestion
```

2021-02-22 14:51 UTC, Lucia-Fonseca commented on skypy/galaxies/spectrum.py
```suggestion
```

2021-02-22 14:51 UTC, Lucia-Fonseca commented on skypy/utils/special.py
```suggestion
```

2021-02-22 14:54 UTC, ntessore commented
> Delete blank lines

Docstrings should end with a blank line. Please follow the [numpydoc reference](https://numpydoc.readthedocs.io/en/latest/format.html).

2021-06-15 15:18 UTC, Lucia-Fonseca approved these changes
Good to go

2021-06-15 15:27 UTC, merged