Fix contributor guidelines link
skypyproject/skypy pull request #449
Opened 2021-03-05 10:29 UTC by Lucia-Fonseca

## Description
This PR fixes the link for the Contributing Guidelines in the README.rst file. Merging this PR closes #448 .
## Checklist
- [x] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/main/CONTRIBUTING.rst)
- [ ] Write unit tests
- [ ] Write documentation strings
- [x] Assign someone from your working team to review this pull request
- [x] Assign someone from the infrastructure team to review this pull request

2021-03-05 11:08 UTC, rrjbca requested changes
This is a regression; the page name has been changed from upper to lower case since the last release. Wait on the discussion in #448 before proceeding.

2021-04-22 13:54 UTC, rrjbca commented on README.rst
> +.. _Contributor Guidelines: https://skypy.readthedocs.io/en/stable/developer/CONTRIBUTING.html
```suggestion
.. _Contributor Guidelines: https://skypy.readthedocs.io/en/latest/developer/contributing.html
```

2021-04-22 13:55 UTC, ntessore approved these changes

2021-04-22 13:59 UTC, rrjbca approved these changes

2021-04-22 13:59 UTC, merged